### ISSUE TITLE
Error with input in IE

### ISSUE THREAD

**Issue by ghost** [ali-irawan/jquery-inputformat#1]
I am receiving the following error when using your jQuery InputFormat plugin and Internet Explorer v11.0.9600.17691 as shown below:-

I am trying to input the value 0.12 and am getting the error.

![ieproblem](https://cloud.githubusercontent.com/assets/11690768/6879981/a481b45c-d521-11e4-9e4e-5db1b9b341a6.jpg)

Answer:
var dot = unformatted.toString().indexOf(_decimalSep);

**Comment by ali-irawan** [comment]
Thanks, for posting this.
This fixed will be added in the source.
